general:
  name: "baseline"
  output_folder: "pipeline_outputs/xray_baseline"
  batch_size: 16
  apply_diffusion_guidance: true
  seed: 0
  denoiser_time_index: 0
  save_structures_every_n_steps: -1
  recycle_structures: 
    should_recycle: false
    recycle_connection: null # false or [a,b] where it will recycle from step a to step b by adding the noise and restaring from iteration b [b < a]
    recycle_n_times: -1

protein:
  assembly_identifier: null
  sequences:
    - count: 1
      sequence: "QATSQPINFQVQKDGSSEKSHMDDYMQHPGKVIKQNNKYYFQTVLNNASFWKEYKFYNANNQELATTVVNDNKKADTRTINVAVEPGYKSLTTKVHIVVPQINYNHRYTTHLEFEKAIPTLA"
  pdb_id: "2o1a"
  chains_to_use: [0]
  residue_range: [[34, 37]]
  reference_pdb: "pipline_inputs/pdbs/2o1a/2o1a_chain_A_altloc_A_fixed.pdb" # this is passed to the model manager and used to save the pdb
  reference_raw_pdb: pipline_inputs/pdbs/2o1a/2o1a.pdb # this is used to save the merged pdb
  reference_raw_pdb_chain: A # this is used to save the merged pdb
  contains_missing_atoms: false
  should_fill_mask: false
  should_align_to_chains: [0]

model_manager:
  N_cycle: 10
  chunk_size: 256
  diffusion_N: 200
  gamma0: 0.8
  gamma_min: 1.0
  noise_scale_lambda: 1.003
  step_scale_eta: 1
  msa_save_dir: "./alignment_dir"
  msa_embedding_cache_dir: "./msa_cache"
  model_checkpoint_path: "./src/af3-dev/release_model/model_v0.2.0.pt"
  dump_dir: "proteniX_output"
  use_msa: true
  time_profiler: false
  memory_profiler: false
  pairformer_mixed_precision: false
  reapply_noise_if_fixed_ROI: false

wandb:
  login_key: wandb_login_key
  mode: "disabled" # options are "disabled" or "online"
  project: wandb_project_name

loss_function:
  loss_function_type: ["density"] # "density", "pairwise", "heavy_noe", "nmr", "sf_density"
  violation_loss_weight: 0.0
  bond_length_loss_weight: 0.0
  normalize_losses_by_main_loss: false
  start_guidance_from: 0

  rmsd_loss_function:
    reference_files: ["nmr_pdbs/6f3k.pdb"]
    top_k: 30 # when calculating the loss, taking the distances for the top_k atoms and calculating only on them
    mean_loss_weight: 1 # the weight for the loss that compares the atom locations mean across the batch with the mean of the references
    distance_loss_weight: 0 # the weight for the loss that compares the distances of the closest confirmation to each target

  density_loss_function:
    density_file: "pipline_inputs/densities/2o1a/2o1a_box_xyz.ccp4"
    mtz_file: "pipline_inputs/mtzs/2o1a/2o1a.mtz" # for rfactor calculation
    rmax: 5
    bond_max_threshold: 2.1
    ccp4_env_path: "/nfs/scistore20/bronsgrp/amaddipa/ccp4-8.0/bin/ccp4.setup-sh"
    phenix_env_path: "/nfs/scistore20/bronsgrp/amaddipa/phenix-1.21.2-5419/phenix_env.sh"
    map_type: "end"
    occ_lambda: 0.7
    reference_pdbs: ["pipline_inputs/pdbs/2o1a/2o1a_chain_A_altloc_A_fixed.pdb", "pipline_inputs/pdbs/2o1a/2o1a_chain_A_altloc_B_fixed.pdb"] # these pdbs are used to extract the region of intreset in the density map, and align the structures to the density
    weight: 1
  
  pairwise_loss_function:
    reference_pdb: "nmr_pdbs/6f3k/6f3k_fixed.pdb"
    rmax: 5
    atom_type: "N"

  nmr_loss_function:
    weight: 1.0
    reference_nmr: "pipeline_inputs/nmr_restraints/1u0p_or_code.csv"
    pdb_file: "pipeline_inputs/nmr_pdbs/1u0p/1u0p_fixed.pdb"
    methyl_rdc_file: ""
    methyl_rdc_scale: 0.0
    amide_rdc_file:  ""
    amide_rdc_scale: 0.0
    amide_relax_file: ""
    amide_relax_scale: 0.0
    methyl_relax_scale: 0.0
    methyl_relax_file: ""
    noe_scale: 1.0
    iid_loss: false

  heavy_noe_loss_function:
    reference_nmr: "pipeline_inputs/nmr_restraints/6f3k_or_code.csv"
    pdb_file: "pipeline_inputs/nmr_pdbs/6f3k/6f3k_fixed.pdb"
    iid_loss: false

  cryoesp_loss_function:
    reference_pdb: "pipeline_inputs/pdbs/6w0o/pdb6w0o_seqaligned_1res.pdb"
    esp_file: "pipeline_inputs/pdbs/6w0o/emd_21501.map" # emd_41880 (e) emd_41877 (b)
    is_assembled: true
    emdb_resolution: 2.77
    global_b_factor: 100.0
    reduced_D: 300
    use_Coloumb: false
    guide_only_ROI: false
    aling_only_outside_ROI: false
    log_bond_length_loss: false
    rmax_for_mask: 2.1
    rmax_for_esp: 10.0
    rmax_for_final_bfac_fitting: 2.1
    optimize_bfactor: true
    reapply_b_factor: false
    reapply_is_learnable: false
    combinatorially_best_alignment: false
    alignment_strategy: "global_density_gradient_ascent"
    reuse_multimer_alignment: false
    reordering_every: 201

    gradient_ascent_parameters:
      steps: 30
      lr_t_A: 1000
      lr_r_deg: 1000
      reduction: "mean"
      per_step_t_cap_voxels: 3.0
      Bfac: 300
      bfactor_minimum: 300
      n_random: 20000
      t_init_box_edge_voxels: 5.0
      momentum_factor: 0.9

    symmetry: 
      symmetry_type: "per_blob_gradient_alignment"
      reapply_symmetry_every: true

    sinkhorn: 
      percentage: 1.0
      p: 2  
      blur: 0.005
      backend: "online" 
      reach: 
      scaling: 0.95
      turn_off_after: 188
      debug_with_rmsd: false
      debias: false
      guide_multimer_by_chains: true
      threshold_to_find_chains: 0.1

    dihedrals:
      use_dihedrals: "from_nmr" # [false, "from_gt", "from_nmr"]
      dihedral_loss_weight: 0.0
      dihedrals_file: "pipeline_inputs/pdbs/6w0o/talos.tab" # don't have it now, so None

diffusion_process:
  guidance:
    step_size: 0.1
    guidance_direction_scale_factor: 1.0
    normalize_gradients: true
    guidance_scale_gradually_increase: false

