general:
  name: "baseline"
  output_folder: "pipeline_outputs/baseline"
  batch_size: 16
  apply_diffusion_guidance: true
  seed: 0

protein:
  sequence: "QATSQPINFQVQKDGSSEKSHMDDYMQHPGKVIKQNNKYYFQTVLNNASFWKEYKFYNANNQELATTVVNDNKKADTRTINVAVEPGYKSLTTKVHIVVPQINYNHRYTTHLEFEKAIPTLA"
  pdb_id: "2o1a"
  residue_range: [34, 37]
  reference_pdb: "pipline_inputs/pdbs/2o1a/2o1a_chain_A_altloc_A_fixed.pdb" # this is passed to the model manager and used to save the pdb
  reference_raw_pdb: pipline_inputs/pdbs/2o1a/2o1a.pdb # this is used to save the merged pdb
  reference_raw_pdb_chain: A # this is used to save the merged pdb


model_manager:
  N_cycle: 10
  chunk_size: 256
  diffusion_N: 200
  gamma0: 0.8
  gamma_min: 1.0
  noise_scale_lambda: 1.003
  step_scale_eta: 1
  msa_save_dir: "./alignment_dir"
  msa_embedding_cache_dir: "./msa_cache"
  model_checkpoint_path: "./src/af3-dev/release_model/model_v0.2.0.pt"
  dump_dir: "proteinX_output"
  use_msa: true

wandb:
  login_key: wandb_login_key
  mode: "disabled" # options are "disabled" or "online"
  project: wandb_project_name

loss_function:
  loss_function_type: "density" # "rmsd", "density", "pairwise", "heavy_noe", "hydrogen_noe", "sf", "sf_density", "epr"
  violation_loss_weight: 0.0
  bond_length_loss_weight: 0.0

  rmsd_loss_function:
    reference_files: ["nmr_pdbs/6f3k.pdb"]
    top_k: 30 # when calculating the loss, taking the distances for the top_k atoms and calculating only on them
    mean_loss_weight: 1 # the weight for the loss that compares the atom locations mean across the batch with the mean of the references
    distance_loss_weight: 0 # the weight for the loss that compares the distances of the closest confirmation to each target

  density_loss_function:
    density_file: "pipline_inputs/densities/2o1a/2o1a_box_xyz.ccp4"
    mtz_file: "pipline_inputs/mtzs/2o1a/2o1a.mtz" # for rfactor calculation
    rmax: 5
    bond_max_threshold: 2.1
    ccp4_env_path: "/nfs/scistore20/bronsgrp/amaddipa/ccp4-8.0/bin/ccp4.setup-sh"
    phenix_env_path: "/nfs/scistore20/bronsgrp/amaddipa/phenix-1.21.2-5419/phenix_env.sh"
    map_type: "end"
    occ_lambda: 0.7
    reference_pdbs: ["pipline_inputs/pdbs/2o1a/2o1a_chain_A_altloc_A_fixed.pdb", "pipline_inputs/pdbs/2o1a/2o1a_chain_A_altloc_B_fixed.pdb"] # these pdbs are used to extract the region of intreset in the density map, and align the structures to the density
  
  sf_density_loss_function:
    mtz_file: "pipline_inputs/mtzs/4ole/4ole.mtz"
    density_file: null
    reference_pdbs: ["pipline_inputs/pdbs/4ole/4ole_chain_B_altloc_A_fixed.pdb", "pipline_inputs/pdbs/4ole/4ole_chain_B_altloc_B_fixed.pdb"] # these pdbs are used to extract the region of intreset in the density map, and align the structures to the density
    mtz_file: "pipline_inputs/mtzs/4ole/4ole.mtz"
    rmax: 5
    compare_zone_of_interest_only: true
    compare_sfs: false
    altloc_region_b_factor: 25
    loss_threshold: 0.2
    parameter_lr: 0.1
    optimize_unisotropic: true
    n_bins: 20

  pairwise_loss_function:
    reference_pdb: "nmr_pdbs/6f3k/6f3k_fixed.pdb"
    rmax: 5
    atom_type: "N"

  epr_loss_function:
    constraints_file: "pipeline_inputs/epr/pre_distances.csv"
    rotamers_statistics_file: "pipeline_inputs/epr/rotamer1_R1A_298K_2015.csv"
    rotamers_structures_folder: "pipeline_inputs/epr/rotamer1_R1A_298K_2015"

  hydrogen_noe_loss_function:
    reference_nmr: "pipeline_inputs/nmr_restraints/6f3k_or_code.csv"
    pdb_file: "pipeline_inputs/nmr_pdbs/6f3k/6f3k_fixed.pdb"
    methyl_rdc_file: "" #"pipeline_inputs/nmr_s_2/6f3k_methyl_s2.csv" # "pipeline_inputs/nmr_s_2/ubi_methyl_rdc.csv" # nmr_s_2/ubi_nh_rdc.csv  nmr_s_2/ubi_methyl_s2.csv  nmr_s_2/ubi_solution_S2.csv
    methyl_rdc_scale: 0.0
    amide_rdc_file: "" #"nmr_s_2/ubi_nh_rdc.csv" 
    amide_rdc_scale: 0.0 
    amide_relax_file: "" #"pipeline_inputs/nmr_s_2/ubi_solution_S2.csv" 
    amide_relax_scale: 0.0
    methyl_relax_scale: 0.0
    methyl_relax_file: "" #nmr_s_2/ubi_methyl_relaxation.csv
    noe_scale: 1.0
    op_n_bootstrap: 0
    iid_loss: false

  heavy_noe_loss_function:
    reference_nmr: "pipeline_inputs/nmr_restraints/6f3k_or_code.csv"
    pdb_file: "pipeline_inputs/nmr_pdbs/6f3k/6f3k_fixed.pdb"
    iid_loss: false


  sf_loss_function:
    reference_mtz: "pipeline_inputs/mtzs/1d3z/1d3z.mtz"
    rmsd_alignment: true # if this is true, at each iteration RMSD will be done with respect to the reference structure
    optimize_alignment: false # if rmsd_alignment is false, this will indicate if to optimize the rotations and translations or not
    guide_residue_range: true # if this is true, the guidance will be only on the atom in the residue range, if this is false, we will optimize the entire protein
    isotropic_parameters_lr: 0.01

diffusion_process:
  guidance:
    step_size: 0.09
    guidance_direction_scale_factor: 1.0 # this will scale the guidance direction only and not the extra optimized parameters (like bfactor)
    normalize_gradients: true # whether to normalize the gradients or not

